from configuration import Configuration
configurations = Configuration()

configurations_dict = \
{
"COMBINE_EMISSIONS_WEIGHT": 1,
"CLONE_STATE_WEIGHT": 0,
"CLONE_EMISSION_WEIGHT": 1,
"ADD_STATE_WEIGHT": 0,
"REMOVE_STATE_WEIGHT": 0,
"ADD_TRANSITION_WEIGHT": 0,
"REMOVE_TRANSITION_WEIGHT": 0,
"ADD_SEGMENT_TO_EMISSION_WEIGHT": 1,
"REMOVE_SEGMENT_FROM_EMISSION_WEIGHT": 1,
"CHANGE_SEGMENT_IN_EMISSION": 1,
"ADD_EMISSION_TO_STATE_WEIGHT": 1,
"REMOVE_EMISSION_FROM_STATE_WEIGHT": 1,
"INCREASE_TRANSITION_WEIGHT_WEIGHT": 0,
"DECREASE_TRANSITION_WEIGHT_WEIGHT": 0,
"INCREASE_EMISSION_WEIGHT_WEIGHT": 0,
"DECREASE_EMISSION_WEIGHT_WEIGHT": 0,


"MAX_NUM_OF_INNER_STATES": 5,
"MIN_NUM_OF_INNER_STATES": 1,

"ADD_RULE": 1,
"REMOVE_RULE": 1,
"CHANGE_RULE": 1,
"DEMOTE_RULE": 1,

"MUTATE_TARGET": 1,
"MUTATE_CHANGE": 1,
"MUTATE_LEFT_CONTEXT": 1,
"MUTATE_RIGHT_CONTEXT": 1,
"MUTATE_OBLIGATORY": 1,

"ADD_TO_FEATURE_BUNDLE": 1,
"REMOVE_FROM_FEATURE_BUNDLE": 1,

"ADD_FEATURE_BUNDLE": 1,
"REMOVE_FEATURE_BUNDLE": 1,
"CHANGE_EXISTING_FEATURE_BUNDLE": 1,

"ADD_FEATURE": 1,
"REMOVE_FEATURE": 1,
"CHANGE_FEATURE_VALUE": 1,

"DATA_ENCODING_LENGTH_MULTIPLIER": 1,
"HMM_ENCODING_LENGTH_MULTIPLIER": 1,
"RULES_SET_ENCODING_LENGTH_MULTIPLIER": 1,

"CORPUS_DUPLICATION_FACTOR": 1,

"MORPHEME_BOUNDARY_FLAG": False,
"LENGTHENING_FLAG": False,
"UNDERSPECIFICATION_FLAG": False,
"RESTRICTIONS_ON_ALPHABET": False,
"WORD_BOUNDARY_FLAG": False,

"MAX_FEATURE_BUNDLE_IN_CONTEXT": 2,

"INITIAL_TEMPERATURE": 50,
"THRESHOLD": 10**-2,
"COOLING_RATE": 0.9995,
"DEBUG_LOGGING_INTERVAL": 50,
"STEPS_LIMITATION": float('inf'),

"LINEAR_DECAY": False
}

configurations.load_configurations_from_dict(configurations_dict)